#--------1---------2---------3---------4---------5---------6---------7---------8---------9---------0
require:
  - rubocop-rspec
# The idea is to bring this file in line with the default configuration:
# https://github.com/rubocop-hq/rubocop-rspec/blob/master/config/default.yml.
# We're not quite at a point to do that yet.
AllCops:
  TargetRubyVersion: 2.5
RSpec/MultipleExpectations:
  Max: 2