version: '3'
services:
  unicorn4:
    build:
      dockerfile: docker/Dockerfile_unicorn4
      context: .
      args:
        port: 3010
    volumes:
      - ./run-data/unicorn4:/tmp/unicorn4
    ports:
      - "3010:3010"
  test_harness:
    build:
      dockerfile: docker/Dockerfile_testrunner
      context: .
    volumes:
      - ./run-data:/run-data
    environment:
      - TEST_HOSTS=unicorn4 # Update this with the service name - the script parses this env var to iterate over test instances
      - DOCKER=true
    depends_on:
      - unicorn4
volumes:
  run-data: