version: '3'
services:
  db:
    image: bitnami/mongodb:latest
    restart: always
    environment:
      MONGODB_USERNAME: mongotest
      MONGODB_PASSWORD: mongotestpass
      MONGODB_DATABASE: dummy_production
      ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "27017:27017"
    networks:
      - webproxy
  base:
    build:
      dockerfile: ./docker/performance/Dockerfile_base
      context: .
    links:
     - db
    depends_on:
      - db
    networks:
      - webproxy
  agent:
    depends_on:
      - base
    build:
      dockerfile: ./docker/performance/Dockerfile_agent
      context: ../vulneruby_engine
    networks:
      - webproxy
  without-agent:
    depends_on:
      - base
    build:
      dockerfile: ./docker/performance/Dockerfile_no_agent
      context: .
    env_file:
      - ./docker/.env
    ports:
      - "3009:3009"
    volumes:
      - ./run-data/no_agent:/tmp/agent
    networks:
      - webproxy
  with-agent-assess:
    depends_on:
      - agent
    build:
      dockerfile: ./docker/performance/Dockerfile_assess
      context: .
    env_file:
      - ./docker/.env
    ports:
      - "3009:3009"
    volumes:
      - ./run-data/assess:/tmp/agent
    networks:
      - webproxy
  with-agent-protect:
    depends_on:
      - agent
    build:
      dockerfile: ./docker/performance/Dockerfile_protect
      context: .
    env_file:
      - ./docker/.env
    volumes:
      - ./run-data/protect:/tmp/agent
    ports:
      - "3009:3009"
    networks:
      - webproxy
networks:
  webproxy:
    driver: bridge
volumes:
  run-data: