development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      database: dummy_development
      hosts:
        - db:27017
      options:
        # The name of the user for authentication.
        user: 'mongotest'
        # The password of the user for authentication.
        password: 'mongotestpass'
        # The user's database roles.
        roles:
          - 'dbOwner'
        # The timeout in seconds for selecting a server for an operation. (default: 30)
        server_selection_timeout: 20
  options:
test:
  clients:
    default:
      database: dummy_test
      hosts:
        - db:27017
      options:
        read:
          mode: :primary
        max_pool_size: 5
