FROM ruby-app-test_agent

# Set port for testing
ARG PORT_ARG=3012
ENV PORT=$PORT_ARG

# Enable the web server gem
ENV UNICORN_5_TEST=true

# Name and run the application
RUN ./docker/app_name_generator.sh Unicorn5 >> /tmp/app_name.txt
CMD CONTRAST__APPLICATION__NAME=$(cat /tmp/app_name.txt) bundle exec unicorn -p $PORT -c ./spec/dummy/config/unicorn.rb ./spec/dummy/config.ru