FROM ruby-app-test_agent

# Set port for testing
ARG PORT_ARG=3008
ENV PORT=$PORT_ARG

# Enable the web server gem
ENV PASSENGER_TEST=true

# Name and run the application
RUN ./docker/app_name_generator.sh Passenger >> /tmp/app_name.txt
CMD CONTRAST_CONFIG_PATH=/app/contrast_security.yaml CONTRAST__APPLICATION__NAME=$(cat /tmp/app_name.txt) bundle exec rails s -p $PORT
