FROM ruby:2.7
ARG PORT_ARG=3010

RUN apt-get update && apt-get install -y build-essential coreutils

WORKDIR app

COPY agent/* agent/
COPY Gemfile .
COPY Gemfile.lock .
COPY vulneruby_engine.gemspec .
COPY lib/vulneruby_engine/version.rb ./lib/vulneruby_engine/version.rb

# Used in CI to install gem dropped in ./agent/ directory
RUN gem install ./agent/contrast-agent.gem

ENV UNICORN_4=true
RUN bundle install --with unicorn_4

ENV CI_TEST=true

COPY . .
RUN rm **/*.log | true

# this is used by the volume in docker-compose
RUN mkdir -p /tmp/unicorn4/messages
ENV CONTRAST__AGENT__LOGGER__PATH=/tmp/unicorn4/agent.log
ENV CONTRAST__AGENT__SERVICE__LOGGER__PATH=/tmp/unicorn4/service.log
ENV CONTRAST__API__REQUEST_AUDIT__PATH=/tmp/unicorn4/messages

RUN ./docker/app_name_generator.sh Unicorn4 >> /tmp/app_name.txt
RUN cat /tmp/app_name.txt

RUN bundle exec rails db:migrate

ENV UNICORN_4_TEST=true
ENV PORT=$PORT_ARG

CMD CONTRAST__APPLICATION__NAME=$(cat /tmp/app_name.txt) bundle exec unicorn -p $PORT -c ./spec/dummy/config/unicorn.rb ./spec/dummy/config.ru