FROM ruby-app-test_agent

# Set port for testing
ARG PORT_ARG=3010
ENV PORT=$PORT_ARG

# Enable the web server gem
ENV THIN_TEST=true

# Name and run the application
RUN ./docker/app_name_generator.sh Thin >> /tmp/app_name.txt
CMD CONTRAST__APPLICATION__NAME=$(cat /tmp/app_name.txt) bundle exec thin -p $PORT -R /app/spec/dummy/config.ru start
