# Just default. Env var takes precedence.
ARG RUBY_VER=3.0
FROM ghcr.io/contrast-security-oss/vulneruby_engine/base:${RUBY_VER}

ENV CI_TEST=true
COPY agent/* agent/
RUN rm contrast_security.yml || true
COPY contrast_security.yml contrast_security.yml
RUN gem install ./agent/contrast-agent.gem

CMD tail -f /tmp/tail_me
