FROM ruby-app-test_agent

# Set port for testing
ARG PORT_ARG=3014
ENV PORT=$PORT_ARG

# Enable the web server gem
ENV UNICORN_MAX=true
RUN bundle config set with 'unicorn_max'

RUN AGENT_PATH=`gem which contrast-agent` bundle update && bundle install

# So we may use whatever command we want to trigger rake, to be sure
# that the agent is not braking the rake task

ENV UNICORN_MAX_TEST=true

# Add dependency for AgentLib gem support.
RUN apt-get install musl-dev -y && ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1

# Check Database Version
RUN bundle exec rake db:version

# Name and run the application
RUN ./docker/app_name_generator.sh Unicorn_max >> /tmp/app_name.txt
CMD redis-server & cat /tmp/app_name.txt && CONTRAST__APPLICATION__NAME=$(cat /tmp/app_name.txt) bundle exec unicorn -p $PORT -c ./spec/dummy/config/unicorn.rb ./spec/dummy/config.ru
