# Just default. Env var takes precedence.
ARG RUBY_VER=3.0
FROM ghcr.io/contrast-security-oss/vulneruby_engine/base:${RUBY_VER}

ENV CI_TEST=true
COPY agent/* agent/
RUN rm contrast_security.yaml || true
COPY contrast_security.yaml contrast_security.yml
RUN mkdir config && ls
COPY spec/dummy/config/contrast_security.yaml config/contrast_security.yaml
RUN gem install ./agent/contrast-agent.gem

CMD tail -f /tmp/tail_me
