FROM ruby-app-test_agent

# Set port for testing
ARG PORT_ARG=3013
ENV PORT=$PORT_ARG

# Enable the web server gem
ENV UNICORN_MIN=true
RUN bundle config set with 'unicorn_min'

RUN AGENT_PATH=`gem which contrast-agent` bundle update && bundle install

# So we may use whatever command we want to trigger rake, to be sure
# that the agent is not braking the rake task

ENV UNICORN_MIN_TEST=true

# Check Database Version
RUN bundle exec rake db:version

# Name and run the application
RUN ./docker/app_name_generator.sh Unicorn_min >> /tmp/app_name.txt
RUN curl -fsSL https://packages.redis.io/gpg | gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg \
    echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/redis.list \
    apt-get update && apt-get install -y redis
CMD redis-server & cat /tmp/app_name.txt && CONTRAST__APPLICATION__NAME=$(cat /tmp/app_name.txt) bundle exec unicorn -p $PORT -c ./spec/dummy/config/unicorn.rb ./spec/dummy/config.ru
