# Just default. Env var takes precedence.
ARG RUBY_VER=2.5

FROM ruby:${RUBY_VER}

RUN apt-get update && apt-get install -y build-essential coreutils chromium chromium-chromedriver

WORKDIR app

ENV DISABLE_DATABASE_ENVIRONMENT_CHECK=1
ENV SECRET_KEY_BASE=foobarblah
ENV RAILS_ENV=production
ENV APP_HOME=./

COPY . .
RUN rm **/*.log | true

RUN gem install bundler

ENV PUMA=true
ENV THIN=true

RUN bundle config set with 'puma' 'thin'
RUN bundle install

# this is used by the volume in docker-compose
RUN mkdir -p /tmp/agent/messages
RUN mkdir -p tmp/pids
ENV CONTRAST__AGENT__LOGGER__PATH=/tmp/agent/agent.log
ENV CONTRAST__AGENT__SERVICE__LOGGER__PATH=/tmp/agent/service.log
ENV CONTRAST__API__REQUEST_AUDIT__PATH=/tmp/agent/messages
ENV APP_LOG=/tmp/agent/app.log

RUN bundle exec rake app:assets:precompile
RUN bundle exec rails db:migrate

# Just in case, clean up local.
RUN rm ./contrast_security.yaml ./spec/dummy/contrast_security.yaml || true
RUN rm ./*log ./spec/dummy/*log || true
RUN rm ./agent || true

RUN touch /tmp/tail_me

CMD tail -f /tmp/tail_me
