FROM ruby:2.7

WORKDIR app
RUN apt-get update -y && apt-get install xvfb -y

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update && apt-get install -y google-chrome-stable

COPY Gemfile .
COPY Gemfile.lock .
COPY vulneruby_engine.gemspec .
COPY lib/vulneruby_engine/version.rb ./lib/vulneruby_engine/version.rb

RUN bundle install

COPY spec/integration ./spec/integration

RUN cd spec/integration && ls

CMD bundle exec ruby ./spec/integration/runner.rb