# Just default. Env var takes precedence.
# These arguments are assigned by script if run locally and must remain empty.
ARG RUBY_VER=''
ARG DISTRO=''

FROM ruby:${RUBY_VER}${DISTRO}

# DEBIAN DISTRO UPDATES
RUN apt-get update && apt-get install -y build-essential coreutils git libsqlite3-dev gnupg pkg-config libxml2-dev libxslt-dev make autoconf automake
# Set up Redis for Sidekiq testing
RUN curl -fsSL https://packages.redis.io/gpg | gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg \
    echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/redis.list \
    apt-get update && apt-get install -y redis
# ALPINE DISTRO UPDATES
# RUN apk update && apk add --update autoconf automake bash build-base coreutils curl git libxml2 libxml2-dev libxslt libxslt-dev nodejs openssh openssl openssl-dev perl ruby-nokogiri sqlite sqlite-dev tar shared-mime-info protobuf tzdata redis

WORKDIR app

ENV DISABLE_DATABASE_ENVIRONMENT_CHECK=1
ENV SECRET_KEY_BASE=foobarblah
ENV RAILS_ENV=production
ENV APP_HOME=./

COPY . .
RUN rm **/*.log | true
RUN rm -rf spec/dummy/node_modules | true \
    rm -rf spec/dummy/yarn.lock | true

RUN gem install bundler

ENV PUMA=true
ENV THIN=true

# If ruby is 3.0 then use ffi 1.15.5:
RUN if [ "$RUBY_VER" = "3.0" ]; \
    then echo "RUBY_VER is 3.0" && export CONTRAST__PIPELINE__RUN=true \
    && bundle config build.ffi -- --disable-system-libffi \
    && gem install ffi -v 1.15.5 -- -- disable-system-libffi; \
    fi


RUN bundle config set with 'puma' 'thin'
RUN bundle config force_ruby_platform true \
    && bundle config build.nokogiri --use-system-libraries
RUN bundle install

# We need to run npm install or yarn install to be able to run mongoid in rails
RUN apt-get remove -y cmdtest && apt-get remove -y yarn && apt-get clean \
&& apt-get install -y curl software-properties-common \
&& curl -sL https://deb.nodesource.com/setup_18.x | bash - \
&& apt-get install -y nodejs && npm install -g npm@latest \
&& cd ./spec/dummy/ && npm install
RUN cd ./

# ALPINE-UPDATES-NPM

# this is used by the volume in docker-compose
RUN mkdir -p /tmp/agent/messages
RUN mkdir -p tmp/pids
ENV CONTRAST__AGENT__LOGGER__PATH=/tmp/agent/agent.log
ENV CONTRAST__AGENT__SERVICE__LOGGER__PATH=/tmp/agent/service.log
ENV CONTRAST__API__REQUEST_AUDIT__PATH=/tmp/agent/messages
ENV APP_LOG=/tmp/agent/app.log

RUN bundle exec rake app:assets:precompile
RUN bundle exec rails db:migrate

# Just in case, clean up local.
RUN rm ./contrast_security.yaml ./spec/dummy/contrast_security.yaml || true
RUN rm ./*log ./spec/dummy/*log || true
RUN rm ./agent || true

RUN touch /tmp/tail_me
EXPOSE 3000
CMD tail -f /tmp/tail_me
