FROM ruby-app-test_agent

# Set port for testing
ARG PORT_ARG=3011
ENV PORT=$PORT_ARG

# Because we also test Unicorn 5, we have to turn that off and re-install to get Unicorn 4
ENV UNICORN_4=true
RUN bundle config set with 'unicorn_4'


RUN AGENT_PATH=`gem which contrast-agent` bundle update && bundle install


# Enable the web server gem
ENV UNICORN_4_TEST=true

# So we may use whatever command we want to trigger rake, to be sure
# that the agent is not braking the rake task

# Check routes
RUN bundle exec rake routes

# Name and run the application
RUN ./docker/app_name_generator.sh Unicorn4 >> /tmp/app_name.txt
CMD cat /tmp/app_name.txt && CONTRAST__APPLICATION__NAME=$(cat /tmp/app_name.txt) bundle exec unicorn -p $PORT -c ./spec/dummy/config/unicorn.rb ./spec/dummy/config.ru
