FROM ruby:2.7
ARG PORT_ARG=3009

# Don't install the agent
ENV CI_TEST=false

RUN apt-get update && apt-get install -y build-essential coreutils

WORKDIR app

ENV SECRET_KEY_BASE=foobarblah
ENV RAILS_SERVE_STATIC_FILES=true
ENV RAILS_ENV=production

COPY agent/* agent/
COPY Gemfile .
COPY Gemfile.lock .
COPY vulneruby_engine.gemspec .
COPY lib/vulneruby_engine/version.rb ./lib/vulneruby_engine/version.rb

ENV PUMA=true
RUN bundle config set with 'puma'
RUN bundle install

COPY . .
RUN rm **/*.log | true

# this is used by the volume in docker-compose
RUN mkdir -p /tmp/puma/messages
ENV CONTRAST__AGENT__LOGGER__PATH=/tmp/puma/agent.log
ENV CONTRAST__AGENT__SERVICE__LOGGER__PATH=/tmp/puma/service.log
ENV CONTRAST__API__REQUEST_AUDIT__PATH=/tmp/puma/messages
ENV APP_LOG=/tmp/puma/app.log

RUN ./docker/app_name_generator.sh Puma >> /tmp/app_name.txt
RUN cat /tmp/app_name.txt

RUN bundle exec rake app:assets:precompile
RUN bundle exec rails db:migrate

ENV PUMA_TEST=true
ENV PORT=$PORT_ARG

RUN mkdir tmp && mkdir tmp/pids
CMD CONTRAST__APPLICATION__NAME=$(cat /tmp/app_name.txt) bundle exec puma -C ./spec/dummy/config/puma.rb ./spec/dummy/config.ru