FROM vulneruby_engine_agent

# Force proper modes
ENV CONTRAST__ENABLE=true
ENV CONTRAST__ASSESS__ENABLE=false
ENV CONTRAST__PROTECT__ENABLE=true

# Name and run the application
RUN ./docker/app_name_generator.sh PerfAgentProtect >> /tmp/app_name.txt
CMD CONTRAST__APPLICATION__NAME=$(cat /tmp/app_name.txt) bundle exec puma -C ./spec/dummy/config/puma.rb ./spec/dummy/config.ru