FROM vulneruby_engine_base

# Force proper modes
ENV CONTRAST__ENABLE=false
RUN gem uninstall contrast-agent

# Name and run the application
RUN ./docker/app_name_generator.sh PerfNoAgent >> /tmp/app_name.txt
CMD CONTRAST__APPLICATION__NAME=$(cat /tmp/app_name.txt) bundle exec puma -C ./spec/dummy/config/puma.rb ./spec/dummy/config.ru